TARGET = libyajl
DLLIB = $(TARGET).so
all:

install:
	mkdir -p d:/ruby/binaries/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib
	cp libyajl.so d:/ruby/binaries/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib/libyajl.so
	cp libyajldll.a d:/ruby/binaries/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib/libyajldll.a
	cp libyajl.def d:/ruby/binaries/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib/libyajl.def
	mkdir -p d:/ruby/binaries/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include/yajl
	cp yajl/*.h d:/ruby/binaries/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include/yajl
